### ISSUE TITLE
Authentication fails under some circumstances

### ISSUE THREAD

**Issue by mfenner** [datacite/cheetoh#1]

**Comment by pameyer** [comment]
One circumstance was observed with existing code using python 2 and urllib2; with the code closely matching the documentation at https://github.com/datacite/cheetoh.

Code snippet which functioned on original API endpoint:
`auth_handler = urllib2.HTTPBasicAuthHandler()
auth_handler.add_password( 'EZID', 'https://ezid.cdlib.org', username, password )
opener = urllib2.build_opener ( auth_handler )`

Using the new endpoint (and credentials):
`auth_handler.add_password( 'EZID', 'https://mds.test.datacite.org',username, password )`
or
`auth_handler.add_password( 'EZID', 'https://mds.datacite.org',username, password )`

fail with HTTP 401 Unauthorized on use at `connection = opener.open( request )` when making a request to `https://mds.test.datacite.org/id/doi:$identifier`

`curl -i --user $username:$password -X POST -d "datacite.title=foo" https://mds.test.datacite.org/id/doi:$identifier` return 400 invalid request, as expected - thinking was to check authentication. Subsequent testing with intentionally invalid credentials showed that this was a poor test, as the invalid credentials also returned 400.  Will re-test with ANVL.

**Comment by pameyer** [comment]
Slightly more troubleshooting from my end:
 - original API docs suggested that no body data was necessary on POST; calls to new API with no body data should succeed. `curl -i --user ${EZID_USER}:invalid -X POST "https://mds.test.datacite.org/id/doi:$indentifier"` returned 400 'missing parameter'
- `works_controller.rb` suggests that `_profile` and `_target` are required parameters; `curl -i --user ${EZID_USER}:invalid -X POST --data-binary '_profile: datacite\n_target: https%3A//dummy.invalid' "https://mds.test.datacite.org/id/doi:$identifier` returns 510 "error: datacite\n_target: https%3A//dummy.invalid profile not supported by this service" ; encoding the '\n' shows same behavior, removing spaces following ':' ANLV separators returns the original 400 invalid response.

Tried troubleshooting locally; ended up with 404 errors on from `load_id`, suggesting that I've missed a step in local dev configuration and not providing useful information about the auth issue.

**Comment by mfenner** [comment]
Thanks a lot Pete, I will have another close look from my end.

**Comment by mfenner** [comment]
@pameyer sorry for the long delay in answering here.

* I double-checked all authentications, and it is working on my end. Make sure your username and password work, e.g. by testing an endpoint in the DataCite MDS API.
* the DataCite MDS API is at `https://mds.test.datacite.org`, so please make sure your authentication requests go to URLs that start with `https://mds.test.datacite.org/id` or `https://mds.test.datacite.org/shoulder`.
* I have moved the documentation to https://support.datacite.org/v1.1/reference#ezid-compatible-api and made some changes, but more work is needed
* authentication is was checked after the request format. I have changed this now so that authentication is always checked first (except GET requests)
* POST will need a body that provides the metadata and target URL
* `profile` defaults to `datacite`, but `datacite` is required to supply metadata.

Please also see my email to the ezidapi beta tester mailing list.

**Comment by mfenner** [comment]
Correction: we can't always return a 401 error first, as the authentication is only checked when talking to the MDS API. The order of events is 

* check that username and password are there
* check that request is well-formed
* send to MDS API

I just pushed a small fix that correctly forwards the 401 status from the MDS API if authentication was not successful.

**Comment by pameyer** [comment]
@mfenner Thanks for all your help (and your email to the google group).

I followed your suggestion of creating an identifier in the UI, then querying with the API to work out the authentication issues.  For the benefit of anyone using HTTP Auth that needs an auth realm; `mds.datacite.org` looks like the correct one to use for `https://mds.test.datacite.org/doi/$identifier` endpoints.  Curl and python2/urllib2 GET requests to this identifier are working.

Still working on getting PUT / create identifier working; but that does not appear to be authentication related (https://github.com/datacite/cheetoh/issues/3).

---
for the benefit of anyone looking for an example: 
`
import urllib2
auth_handler = urllib2.HTTPBasicAuthHandler()
auth_handler.add_password('mds.datacite.org','https://mds.test.datacite.org',os.environ['EZID_USER'],os.environ['EZID_PASSWORD'])
opener = urllib2.build_opener( auth_handler )
`

**Comment by mfenner** [comment]
Thanks Pete. One word of warning: it is easy to accidentally talk to the MDS API instead of the EZID-compatible API, as the hostname is the same and only the path differs. `https://mds.test.datacite.org/doi/$identifier` is for example the MDS API. It is therefore safer to use a different domain name, and I have created `submit.test.datacite.org` for this purpose. Requests to this domain will always go to the EZID-compatible API. Related to this I need to clean up the documentation.

I will close this issue, as authentication seems to be working as expected now.
