### ISSUE TITLE
Unauthorized Error on DataCite Production for EZ API

### ISSUE THREAD

**Issue by shlake** [datacite/cheetoh#11]
UVa has successfully logged on via GUI - mds.datacite.org. & Fabrica. I have created a dataset on the mds UI. 
 
But our problem is with the EZ API login. We used the same username/password on the API as the UI, but are getting “unauthorized” when trying to connect to https://ez.datacite.org through API.

**Comment by procorenguejip** [comment]
I got the same error using the EZ API login in staging environment, but Martin reply me about three weeks ago:
In contrast to the EZID service at CDL this is only an API and has no HTML pages. Therefore there is no login route, but you rather authenticate via basic authentication in the request header. hope this will help

**Comment by UVADave** [comment]
Having problems authenticating to the API running @ https://ez.datacite.org. Have tried username and password provided by Britta and continue to receive an unauthorized error.

2018/03/14 10:47:04 Service (https://ez.datacite.org/shoulder/doi:10.5072/FK2) returns http 401 in 539.744713ms
2018/03/14 10:47:04 Error response body: [error: unauthorized]

Please advise...

**Comment by shlake** [comment]
UVa will get new accounts with only "one" dot.
Then we will test again.

**Comment by shlake** [comment]
Testing with new account name: VIVA.UVA-LIBRA was not successful. @UVADave will work with @mfenner directly.

**Comment by mfenner** [comment]
@shlake You again get a 401 error?

**Comment by shlake** [comment]
@UVADave sent you an email with the details. I can log in to both UIs.

**Comment by mfenner** [comment]
This has been resolved in the latest version, and confirmed by @UVADave.
