### ISSUE TITLE
@profile is not set to :_profile correctly

### ISSUE THREAD

**Issue by mickel1138** [datacite/cheetoh#18]
Not having the `@profile` set correctly is causing the update function to fail because it fails to detect the safe parameter _profile. There is will also not accept the work profile. Status changes and target updates work fine.

https://github.com/datacite/cheetoh/blob/e12ad397fc806793b53e194907bd3c700f3ce822/app/controllers/works_controller.rb#L145

**Comment by mfenner** [comment]
@mickel1138 can you provide an example where the update fails? Is it for example with a DOI in reserved state?

**Comment by mickel1138** [comment]
@mfenner When doing an update POST to the API, using only _profile and the datacite profile parameters (4 of them) the return code is HTTP 400 message: "error: No _profile, _target or _status provided".
Example curl: 
`curl -X POST \
  https://ez.datacite.org/id/10.5072/mehhh \
  -H 'Authorization: Basic YOUR_BASE64_KEYPAIR_HERE=' \
  -H 'Cache-Control: no-cache' \
  -H 'content-type: multipart/form-data;' \
  -F _profile=datacite \
  -F datacite.title=New_Title \
  -F datacite.creator=Test \
  -F datacite.publisher=GRIIDC \
  -F datacite.publicationyear=2018`

When adding the parameters _target and/or _status the return is HTTP 200. And the target changes, but the profile fields are ignored, so the metadata is not changed. Also, changing _profile to something else will result in "error: XXXX profile not supported by this service"

This is done with our test/demo login, we can only have DOI's in "reserved state", so i'm not sure if this is an issue for a DOI in a particular state. And it also does not work in our production environment.

**Comment by mfenner** [comment]
This has been fixed via https://github.com/datacite/datacite/issues/526.
