### ISSUE TITLE
error on doi minting

### ISSUE THREAD

**Issue by kjgarza** [datacite/cheetoh#22]
unpermitted parameter :author only occurs in test

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fjaz)

**Comment by mfenner** [comment]
This has been fixed via https://github.com/datacite/cheetoh/commit/0ddd21f04c7eab05cd6a57880fb486b4da1e4b77.
