### ISSUE TITLE
Status unavailable

### ISSUE THREAD

**Issue by pgwillia** [datacite/cheetoh#23]
POSTing
```
 _status: unavailable | not publicly released
```
Has a response including
```
_status: unavailable | unavailable | not publicly released
```
[See more https://github.com/ualbertalib/jupiter/blob/master/test/vcr/ezid_updating_unavailable.yml#L112]

I suspected that https://github.com/datacite/cheetoh/pull/19/files should fix this but it hasn't.
There is a test in that pull request. Does it pass?

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/cheetoh/commit/b1cc77c9a29738005396ddcdaa4cc982b3cf6389

**Comment by mfenner** [comment]
@pgwillia it looks like  https://github.com/datacite/cheetoh/pull/19 fixed the issue for `PUT` requests, but not `POST`. Added the code in  https://github.com/datacite/cheetoh/commit/b1cc77c9a29738005396ddcdaa4cc982b3cf6389, let me know if that fixes the issue for you.

P.S. Your VCR casette was very helpful.

P.S.S. Feel free to use the ANVL gem I wrote for this application if that helps Jupiter: https://rubygems.org/gems/anvl-converter

**Comment by pgwillia** [comment]
Sorry.  It doesn't look like this is fixed quite yet.

I'm not sure why https://github.com/datacite/cheetoh/blob/b1cc77c9a29738005396ddcdaa4cc982b3cf6389/app/controllers/concerns/doiable.rb#L97 uses '%7' instead of `|`.  Could this be the problem?
