### ISSUE TITLE
differences between DataCiteXML (and encodings?) accepted by original and compatible endpoints

### ISSUE THREAD

**Issue by pameyer** [datacite/cheetoh#3]
`cheetoh` endpoints enforce additional validation on HTTP PUT requests when creating an identifier.  One identified area is that the `identifier` XML element needs to contain the identifier being created (aka - `(:tba)` is no longer accepted).

There may also be differences with base64 encoding accepted by both endpoints.  Manually created identifier at `https://mds.test.datacite.org/datasets?form` using example DataCite XML; identifier is successfully created and GET API requests show correct metadata (spot check, non-exhaustive).  encoding this example and sending it in ALVN `datacite` element along with PUT request to `https://mds.test.datacite.org/doi/$identifier` fail with HTTP 400 bad request.

~Naive investigation of `30c5334046f48c0d0002b0af8fc72050efef0656` suggests that base64 decoding might not be implemented yet.~ (initial investigation likely incorrect).

**Comment by pameyer** [comment]
From @mfenner 's comment; `(:tba)` should be supported now.

Will need further investigation; because it's not base64 encoding (troubleshooting with a cold can lead to technical imprecision).  Still not sure why same XML that would work through the web interface would not work via API.

**Comment by mfenner** [comment]
@pameyer please make sure you use the correct API endpoint. `https://mds.test.datacite.org/doi/$identifier` is the MDS API, for the EZID-compatible API you want to send put requests to `https://mds.test.datacite.org/shoulder/$partial_identifier` or `https://submit.test.datacite.org/doi/$partial_identifier`. I suggest using the latter, to avoid confusion with the MDS API.

**Comment by pameyer** [comment]
@mfenner do you know the HTTP realm for `https://mds.test.datacite.org/` ?

**Comment by mfenner** [comment]
Again, please don't use `https://mds.test.datacite.org/` without a path, as this sends you to another service. Also, the authentication only works in the API, not in the browser, so you shouldn't really need that information.

**Comment by pameyer** [comment]
I'll avoid using that URL without a path.

Based on the authentication issues I had earlier though, I'm pretty sure that I do need a http realm for urllib2 authentication (via API).

**Comment by mfenner** [comment]
I have no experience with urllib2, but I guess your code expects an "authentication challenge". I can implement this, but please also look at ways to send authentication requests without the "authentication challenge", see for example https://stackoverflow.com/questions/4628610/does-urllib2-support-preemptive-authentication-authentication.

**Comment by mfenner** [comment]
@pameyer I have now implemented the "authentication challenge", i.e. the server sends a "WWW-Authenticate" header that includes a realm if you don't provide username and password. Let me know if you still have issues with urllib2.

**Comment by pameyer** [comment]
thanks @mfenner ! - I'll retest and let you know if I see any problems.

**Comment by pameyer** [comment]
Switched to `https://submit.test.datacite.org` (as recommended).  Unable to get auth failures on GET requests within valid credentials; on PUT request was able to get an auth failure and extract realm.

Still getting 400 errors on PUT requests with XML that worked interactively.  Tried several endpoints in case I was using an incorrect one (`https://submit.test.datacite.org/id/%s` , `https://ez.test.datacite.org/id/%s`), same behavior.

Docs (https://support.datacite.org/v1.1/reference#create-doi) suggest that the DOI needs to have `/` in the identifier escaped - @mfenner can you clarify this.
