### ISSUE TITLE
Mint an identifier with and/or without the metadata

### ISSUE THREAD

**Issue by procorenguejip** [datacite/cheetoh#7]
Hello Martin, I am Jehu from mEDRA.
I am trying to mint an identifier to DataCite EZ API but the service endpoint return the following wrong message:
error: A required parameter is missing
Is there any required parameter that the resource need that i should set?

This is the service endpoint: https://ez.test.datacite.org/
The resource is shoulder/doi:10.10.5072/FK2/EUROP.mEDRA.TEST-1

Eventually, could you please provide me some pointers to Java errors list if there is any available?

**Comment by mfenner** [comment]
Jehu,

the required parameters are either `_target` (url) and `_datacite` (metadata), unless you do the following: `_status: reserved`. DOIs can have the status reserved, public or unavailable, for status `reserved` only a DOI is required.

And keep in mind that there are two endpoints to register a DOI:

* mint: service generates DOI name, provide prefix with or without additional characters, e.g. POST /shoulder/DOI:10.5072/fk2
* create: provide DOI name, e.g PUT /id/doi:10.10.5072/FK2/EUROP.mEDRA.TEST-1

**Comment by procorenguejip** [comment]
Thank you Martin,
I didn't care about the tutorial that emphasizes the use of _status:reserved as cited here: 
**Identifier status**: Each identifier in the service has a status. The status is recorded as the value of the "_status" reserved.
Regards.
