### ISSUE TITLE
Going on with integration of EZID API - Error when calling the resource /login

### ISSUE THREAD

**Issue by procorenguejip** [datacite/cheetoh#9]
Hi Martin, I am Jehu from mEDRA,
I have the following error 
**error: bad request - no such identifier** when calling the https://ez.test.datacite.org/login
Is there something that i am missing?

Is there any list of possible error that may occurs?
Thanks.

**Comment by procorenguejip** [comment]
which will be the http response (status, headers, body content) both in case of success and of failure?

**Comment by procorenguejip** [comment]
what kind of errors may occurs

**Comment by mfenner** [comment]
In contrast to the EZID service at CDL this is only an API and has no HTML pages. Therefore there is no login route, but you rather authenticate via basic authentication in the request header.
